# DMG Build Settings for FrameLean
# Custom settings for dmgbuild
# https://dmgbuild.readthedocs.io/en/latest/settings.html

import os.path
import plistlib

# --- Resolved at build time ---
# dmgbuild is invoked from the project root, so relative paths resolve there.
application = defines.get("app", "")
appname = os.path.basename(application)

# Background image is generated by scripts/release/generate_dmg_background.py
# before the DMG build step. Fall back to builtin-arrow if missing.
_BG_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "build", "macos", "dmg_background.png")
_BG_PATH = os.path.normpath(_BG_PATH)


def icon_from_app(app_path):
    """Extract icon path from app bundle."""
    plist_path = os.path.join(app_path, "Contents", "Info.plist")
    with open(plist_path, "rb") as f:
        plist = plistlib.load(f)
    icon_name = plist["CFBundleIconFile"]
    icon_root, icon_ext = os.path.splitext(icon_name)
    if not icon_ext:
        icon_ext = ".icns"
    icon_name = icon_root + icon_ext
    return os.path.join(app_path, "Contents", "Resources", icon_name)


# --- DMG format ---
format = "UDBZ"

# --- Files and symlinks ---
files = [application]
symlinks = {"Applications": "/Applications"}
badge_icon = icon_from_app(application)

# --- Icon positions (aligned with background dotted circles) ---
icon_locations = {appname: (140, 185), "Applications": (520, 185)}

# --- Custom background ---
background = _BG_PATH if os.path.exists(_BG_PATH) else "builtin-arrow"

# --- Window appearance (match background dimensions 660x400) ---
window_rect = ((100, 100), (660, 400))
default_view = "icon-view"

show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
sidebar_width = 180

# --- Icon view ---
show_icon_preview = False
include_icon_view_settings = "auto"
include_list_view_settings = "auto"
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = "bottom"
text_size = 14
icon_size = 128

# --- List view ---
list_icon_size = 16
list_text_size = 12
list_scroll_position = (0, 0)
list_sort_by = "name"
list_use_relative_dates = True
list_calculate_all_sizes = (False,)
list_columns = ("name", "date-modified", "size", "kind", "date-added")
list_column_widths = {
    "name": 300,
    "date-modified": 181,
    "date-created": 181,
    "date-added": 181,
    "date-last-opened": 181,
    "size": 97,
    "kind": 115,
    "label": 100,
    "version": 75,
    "comments": 300,
}
list_column_sort_directions = {
    "name": "ascending",
    "date-modified": "descending",
    "date-created": "descending",
    "date-added": "descending",
    "date-last-opened": "descending",
    "size": "descending",
    "kind": "ascending",
    "label": "ascending",
    "version": "ascending",
    "comments": "ascending",
}
